=== mitre/risk-based-scheduling/case_generator/resources/case_file_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Case File Schema",
  "description": "Array of case objects. Can be elective or add-on cases.",
  "type": "array",
  "items": {
    "description": "Case object.",
    "type": "object",
    "required": ["procedure", "adverseScore", "riskScore", "addon", "priorLocation", "pICU", "durationScore"],
    "properties": {
      "procedure":{
        "description": "Number corresponding to procedure type.",
        "type": "number"
      },
      "adverseScore": {
        "description": "Number corresponding to group for adverse event risk.",
        "type": "number"
      },
      "riskScore": {
        "description": "Number corresponding to group for alternate type of risk (e.g. risk of ICU admission).",
        "type": "number"
      },
      "addon": {
      "description": "Whether case is an addon or not. If this is an elective case file, this field should be False for all cases. If it is an add-on case file, this field should be true for all cases.",
        "type": "boolean"
      },
      "priorLocation": {
        "description": "Where patient came from prior to the procedure. Options are: ICU, FLOOR, OTHER. ",
        "type": "string"
      },
      "pICU": {
        "description": "Probability of a case being discharged to ICU. If want to run without ICU admissions, set every case pICU attribute to 0.",
        "type": "number"
      },
      "durationScore": {
        "description": "Number corresponding to group for case duration category.",
        "type": "number"
      }
      }
  }
}

=== mitre/risk-based-scheduling/case_generator/resources/addon_case_file_template.json
[{"procedure":3,"adverseScore":0.0,"riskScore":1.0,"addon":true,"priorLocation":"OTHER","pICU":0.0166771169,"durationScore":1},{"procedure":3,"adverseScore":4.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.2324372391,"durationScore":1},{"procedure":1,"adverseScore":3.0,"riskScore":4.0,"addon":true,"priorLocation":"ICU","pICU":0.1164897095,"durationScore":1},{"procedure":2,"adverseScore":2.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.4176081379,"durationScore":2},{"procedure":3,"adverseScore":0.0,"riskScore":1.0,"addon":true,"priorLocation":"OTHER","pICU":0.0166771169,"durationScore":1},{"procedure":2,"adverseScore":4.0,"riskScore":3.0,"addon":true,"priorLocation":"FLOOR","pICU":0.1893253252,"durationScore":3},{"procedure":2,"adverseScore":3.0,"riskScore":3.0,"addon":true,"priorLocation":"OTHER","pICU":0.0377495938,"durationScore":2},{"procedure":2,"adverseScore":2.0,"riskScore":5.0,"addon":true,"priorLocation":"FLOOR","pICU":0.2324372391,"durationScore":2},{"procedure":3,"adverseScore":0.0,"riskScore":4.0,"addon":true,"priorLocation":"FLOOR","pICU":0.1164897095,"durationScore":3},{"procedure":1,"adverseScore":1.0,"riskScore":3.0,"addon":true,"priorLocation":"OTHER","pICU":0.0377495938,"durationScore":1},{"procedure":2,"adverseScore":4.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.6038899733,"durationScore":2},{"procedure":2,"adverseScore":4.0,"riskScore":4.0,"addon":true,"priorLocation":"ICU","pICU":0.2189492775,"durationScore":3},{"procedure":3,"adverseScore":0.0,"riskScore":4.0,"addon":true,"priorLocation":"FLOOR","pICU":0.1164897095,"durationScore":3},{"procedure":3,"adverseScore":4.0,"riskScore":3.0,"addon":true,"priorLocation":"ICU","pICU":0.4309196478,"durationScore":3},{"procedure":2,"adverseScore":4.0,"riskScore":3.0,"addon":true,"priorLocation":"ICU","pICU":0.1893253252,"durationScore":3},{"procedure":3,"adverseScore":0.0,"riskScore":1.0,"addon":true,"priorLocation":"OTHER","pICU":0.0166771169,"durationScore":1},{"procedure":2,"adverseScore":2.0,"riskScore":4.0,"addon":true,"priorLocation":"ICU","pICU":0.1164897095,"durationScore":3},{"procedure":2,"adverseScore":4.0,"riskScore":3.0,"addon":true,"priorLocation":"ICU","pICU":0.3560843725,"durationScore":3},{"procedure":2,"adverseScore":3.0,"riskScore":3.0,"addon":true,"priorLocation":"FLOOR","pICU":0.0989719422,"durationScore":2},{"procedure":2,"adverseScore":2.0,"riskScore":4.0,"addon":true,"priorLocation":"FLOOR","pICU":0.5969806199,"durationScore":3},{"procedure":3,"adverseScore":0.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.0975982726,"durationScore":2},{"procedure":2,"adverseScore":4.0,"riskScore":4.0,"addon":true,"priorLocation":"OTHER","pICU":0.1164897095,"durationScore":1},{"procedure":1,"adverseScore":3.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.2324372391,"durationScore":1},{"procedure":1,"adverseScore":2.0,"riskScore":1.0,"addon":true,"priorLocation":"ICU","pICU":0.0453341834,"durationScore":1},{"procedure":3,"adverseScore":0.0,"riskScore":1.0,"addon":true,"priorLocation":"ICU","pICU":0.0166771169,"durationScore":3},{"procedure":2,"adverseScore":4.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.3916694876,"durationScore":2},{"procedure":2,"adverseScore":4.0,"riskScore":3.0,"addon":true,"priorLocation":"ICU","pICU":0.3560843725,"durationScore":3},{"procedure":1,"adverseScore":2.0,"riskScore":3.0,"addon":true,"priorLocation":"OTHER","pICU":0.4309196478,"durationScore":1},{"procedure":2,"adverseScore":4.0,"riskScore":5.0,"addon":true,"priorLocation":"FLOOR","pICU":0.3916694876,"durationScore":3},{"procedure":2,"adverseScore":4.0,"riskScore":3.0,"addon":true,"priorLocation":"ICU","pICU":0.1893253252,"durationScore":3},{"procedure":2,"adverseScore":4.0,"riskScore":3.0,"addon":true,"priorLocation":"FLOOR","pICU":0.4309196478,"durationScore":2},{"procedure":2,"adverseScore":4.0,"riskScore":5.0,"addon":true,"priorLocation":"FLOOR","pICU":0.0975982726,"durationScore":2},{"procedure":2,"adverseScore":2.0,"riskScore":4.0,"addon":true,"priorLocation":"ICU","pICU":0.2189492775,"durationScore":1},{"procedure":3,"adverseScore":0.0,"riskScore":1.0,"addon":true,"priorLocation":"OTHER","pICU":0.0166771169,"durationScore":1},{"procedure":2,"adverseScore":4.0,"riskScore":4.0,"addon":true,"priorLocation":"ICU","pICU":0.1164897095,"durationScore":1},{"procedure":3,"adverseScore":0.0,"riskScore":1.0,"addon":true,"priorLocation":"ICU","pICU":0.0453341834,"durationScore":1},{"procedure":2,"adverseScore":4.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.2324372391,"durationScore":2},{"procedure":3,"adverseScore":4.0,"riskScore":3.0,"addon":true,"priorLocation":"ICU","pICU":0.4309196478,"durationScore":3},{"procedure":3,"adverseScore":0.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.2324372391,"durationScore":2},{"procedure":2,"adverseScore":3.0,"riskScore":2.0,"addon":true,"priorLocation":"ICU","pICU":0.030213122,"durationScore":3},{"procedure":3,"adverseScore":0.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.2324372391,"durationScore":2},{"procedure":2,"adverseScore":2.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.4176081379,"durationScore":1},{"procedure":2,"adverseScore":3.0,"riskScore":5.0,"addon":true,"priorLocation":"FLOOR","pICU":0.0975982726,"durationScore":2},{"procedure":2,"adverseScore":4.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.2324372391,"durationScore":3},{"procedure":2,"adverseScore":4.0,"riskScore":3.0,"addon":true,"priorLocation":"FLOOR","pICU":0.0769874791,"durationScore":3},{"procedure":3,"adverseScore":0.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.2324372391,"durationScore":2},{"procedure":3,"adverseScore":0.0,"riskScore":1.0,"addon":true,"priorLocation":"ICU","pICU":0.0166771169,"durationScore":3},{"procedure":2,"adverseScore":3.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.2324372391,"durationScore":2},{"procedure":2,"adverseScore":3.0,"riskScore":4.0,"addon":true,"priorLocation":"ICU","pICU":0.0449720251,"durationScore":2},{"procedure":2,"adverseScore":4.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.3916694876,"durationScore":2},{"procedure":2,"adverseScore":1.0,"riskScore":5.0,"addon":true,"priorLocation":"OTHER","pICU":0.2324372391,"durationScore":2},{"procedure":3,"adverseScore":0.0,"riskScore":1.0,"addon":true,"priorLocation":"OTHER","pICU":0.0166771169,"durationScore":3},{"procedure":3,"adverseScore":0.0,"riskScore":1.0,"addon":true,"priorLocation":"FLOOR","pICU":0.0166771169,"durationScore":3},{"procedure":2,"adverseScore":3.0,"riskScore":2.0,"addon":true,"priorLocation":"ICU","pICU":0.1564477178,"durationScore":1},{"procedure":2,"adverseScore":4.0,"riskScore":4.0,"addon":true,"priorLocation":"OTHER","pICU":0.1164897095,"durationScore":3},{"procedure":2,"adverseScore":3.0,"riskScore":2.0,"addon":true,"priorLocation":"OTHER","pICU":0.3755217755,"durationScore":3},{"procedure":2,"adverseScore":2.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.2324372391,"durationScore":2},{"procedure":3,"adverseScore":0.0,"riskScore":3.0,"addon":true,"priorLocation":"ICU","pICU":0.0989719422,"durationScore":3},{"procedure":3,"adverseScore":4.0,"riskScore":5.0,"addon":true,"priorLocation":"FLOOR","pICU":0.3391240909,"durationScore":3},{"procedure":2,"adverseScore":4.0,"riskScore":5.0,"addon":true,"priorLocation":"OTHER","pICU":0.0975982726,"durationScore":2},{"procedure":2,"adverseScore":4.0,"riskScore":3.0,"addon":true,"priorLocation":"ICU","pICU":0.3560843725,"durationScore":3},{"procedure":1,"adverseScore":2.0,"riskScore":4.0,"addon":true,"priorLocation":"OTHER","pICU":0.1826194942,"durationScore":1},{"procedure":1,"adverseScore":2.0,"riskScore":5.0,"addon":true,"priorLocation":"FLOOR","pICU":0.589621282,"durationScore":1},{"procedure":3,"adverseScore":0.0,"riskScore":1.0,"addon":true,"priorLocation":"OTHER","pICU":0.0166771169,"durationScore":1},{"procedure":2,"adverseScore":2.0,"riskScore":3.0,"addon":true,"priorLocation":"FLOOR","pICU":0.3426065485,"durationScore":3},{"procedure":3,"adverseScore":0.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.2324372391,"durationScore":3},{"procedure":2,"adverseScore":4.0,"riskScore":5.0,"addon":true,"priorLocation":"OTHER","pICU":0.589621282,"durationScore":2},{"procedure":2,"adverseScore":2.0,"riskScore":3.0,"addon":true,"priorLocation":"OTHER","pICU":0.6419643017,"durationScore":3},{"procedure":2,"adverseScore":4.0,"riskScore":3.0,"addon":true,"priorLocation":"FLOOR","pICU":0.1893253252,"durationScore":3},{"procedure":3,"adverseScore":0.0,"riskScore":4.0,"addon":true,"priorLocation":"ICU","pICU":0.1164897095,"durationScore":3},{"procedure":3,"adverseScore":4.0,"riskScore":3.0,"addon":true,"priorLocation":"ICU","pICU":0.0377495938,"durationScore":2},{"procedure":2,"adverseScore":4.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.6038899733,"durationScore":2},{"procedure":1,"adverseScore":2.0,"riskScore":5.0,"addon":true,"priorLocation":"OTHER","pICU":0.0975982726,"durationScore":1},{"procedure":2,"adverseScore":2.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.2324372391,"durationScore":2},{"procedure":2,"adverseScore":3.0,"riskScore":3.0,"addon":true,"priorLocation":"ICU","pICU":0.3560843725,"durationScore":3},{"procedure":3,"adverseScore":0.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.0975982726,"durationScore":2},{"procedure":2,"adverseScore":2.0,"riskScore":5.0,"addon":true,"priorLocation":"OTHER","pICU":0.2324372391,"durationScore":3},{"procedure":3,"adverseScore":4.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.2324372391,"durationScore":2},{"procedure":1,"adverseScore":2.0,"riskScore":5.0,"addon":true,"priorLocation":"ICU","pICU":0.352538385,"durationScore":1},{"procedure":3,"adverseScore":0.0,"riskScore":1.0,"addon":true,"priorLocation":"OTHER","pICU":0.0166771169,"durationScore":1},{"procedure
